version: 2

updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    assignees:
      - "simonschaufi"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Enable version updates for composer
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    assignees:
      - "simonschaufi"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
